-- Seed data for movies table from movies-data.json
-- This file will be executed on startup if spring.sql.init.mode=always

-- Clear existing data (optional - remove if you want to keep existing data)
-- DELETE FROM movies;

INSERT INTO movies (id, title, original_title, genre, duration, director, movie_cast, description, year, country, release_date, fsk, poster_path, slider_path, ticket_path, is_coming_soon, created_at, updated_at)
VALUES 
(1, 'AB DURCH DIE MITTE', 'Le Million', 'Komödie', '98 Minuten', '', 'Christian Clavier, Rayane Bensetti, Gilles Cohen', 'Eine überraschende Geldsumme bringt das Leben mehrerer Menschen durcheinander. Ab durch die Mitte ist eine turbulente Komödie voller Missverständnisse, Tempo und Situationshumor.', '2025', 'Frankreich', '01.01.2025', 'ab 6 Jahren', '/images/movies/nowshowing/ab_durch_die_mitte.jpg', '/images/movies/nowshowing/ab_durch_die_mitte-slider.png', '/images/tickets/nowshowing/ab_durch_die_mitte-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'BON VOYAGE – BIS HIERHER UND NOCH WEITER', 'On Ira', 'Tragikomödie', '90 Minuten', '', 'Hélène Vincent, Pierre Lottin, David Ayala', 'Eine ungewöhnliche Reise bringt drei sehr unterschiedliche Menschen zusammen. Bon Voyage – Bis hierher und noch weiter ist eine warmherzige Tragikomödie über Abschied, Freundschaft und das Leben.', '2025', 'Frankreich', '01.01.2025', 'ab 12 Jahren', '/images/movies/nowshowing/bon_voyage_bis_hierher_und_noch_weiter.jpg', '/images/movies/nowshowing/bon_voyage_bis_hierher_und_noch_weiter-slider.png', '/images/tickets/nowshowing/bon_voyage_bis_hierher_und_noch_weiter-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'CHARLIE DER SUPERHUND', 'Charlie The Wonderdog', 'Animation / Familie', '92 Minuten', '', '', 'Der liebenswerte Hund Charlie entdeckt, dass in ihm mehr steckt, als er je gedacht hätte. Charlie der Superhund ist ein familienfreundliches Animationsabenteuer über Mut, Freundschaft und Selbstvertrauen.', '2025', 'Kanada', '01.01.2025', 'ab 6 Jahren', '/images/movies/nowshowing/charlie_der_superhund.jpg', '/images/movies/nowshowing/charlie_der_superhund-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'DAS SYSTEM MILCH', 'Das System Milch', 'Dokumentarfilm', '90 Minuten', '', '', 'Wie funktioniert die moderne Milchproduktion wirklich? Das System Milch ist ein aufrüttelnder Dokumentarfilm über industrielle Landwirtschaft, globale Märkte und die Folgen für Tiere, Umwelt und Verbraucher.', '2017', 'Deutschland / Österreich', '01.01.2017', 'ohne Altersbeschränkung', '/images/movies/nowshowing/das_system_milch.jpg', '/images/movies/nowshowing/das_system_milch-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'LES MISÉRABLES – DIE GESCHICHTE VON JEAN VALJEAN', 'Jean Valjean', 'Drama', '98 Minuten', '', 'Grégory Gadebois, Bernard Campan, Alexandra Lamy', 'Die zeitlose Geschichte eines Mannes auf der Suche nach Erlösung. Les Misérables – Die Geschichte von Jean Valjean erzählt von Schuld, Gerechtigkeit und Menschlichkeit.', '2025', 'Frankreich', '01.01.2025', 'ab 12 Jahren', '/images/movies/nowshowing/les_mis_rables_die_geschichte_von_jean_valjean.jpg', '/images/movies/nowshowing/les_mis_rables_die_geschichte_von_jean_valjean-slider.png', '/images/tickets/nowshowing/les_mis_rables_die_geschichte_von_jean_valjean-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 'EXORCISM CHRONICLES – THE BEGINNING', 'Toemarok', 'Anime / Horror', '85 Minuten', '', '', 'Ein düsterer Anime über Dämonen, Rituale und einen uralten Fluch. Exorcism Chronicles – The Beginning bietet intensive Atmosphäre und übernatürlichen Horror.', '2025', 'Südkorea', '01.01.2025', 'ab 16 Jahren', '/images/movies/nowshowing/exorcism_chronicles_the_beginning.jpg', '/images/movies/nowshowing/exorcism_chronicles_the_beginning-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 'GODZILLA MINUS ONE MINUS COLOR', 'Gojira Minus One Minus Color', 'Action / Drama', '125 Minuten', '', 'Ryunosuke Kamiki, Minami Hamabe, Yuki Yamada, Sakura Ando', 'In einer vom Krieg gezeichneten Nachkriegszeit taucht eine zerstörerische Bedrohung aus dem Meer auf. Godzilla Minus One Minus Color erzählt die legendäre Geschichte in einer reduzierten, atmosphärischen Schwarzweißfassung.', '2023', 'Japan', '01.01.2023', 'ab 16 Jahren', '/images/movies/nowshowing/godzilla_minus_one_minus_color.png', '/images/movies/nowshowing/godzilla_minus_one_minus_color-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 'HOME ENTERTAINMENT', 'Home Entertainment', 'Drama', '85 Minuten', '', 'Nadine Dubois, Joseph Bundschuh, Karoline Teska, Anna Brüggemann', 'Ein scheinbar harmloser Fernsehabend entwickelt sich zu einem emotionalen Ausnahmezustand. Home Entertainment erzählt von Nähe, Überforderung und der Zerbrechlichkeit moderner Beziehungen.', '2025', 'Deutschland', '01.01.2025', 'ab 12 Jahren', '/images/movies/nowshowing/home_entertainment.jpg', '/images/movies/nowshowing/home_entertainment-slider.png', '/images/tickets/nowshowing/home_entertainment-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 'IT''S CHRISTMAS – WEIHNACHTEN MIT JONAS KAUFMANN', 'Weihnachten mit Jonas Kaufmann', 'Musik / Event', 'ca. 90 Minuten', '', 'Jonas Kaufmann', 'Ein festliches Konzerterlebnis mit internationalen Weihnachtsliedern. It''s Christmas präsentiert Jonas Kaufmann in einer stimmungsvollen musikalischen Inszenierung.', '2020', 'Deutschland / Österreich', '01.01.2020', 'ohne Altersbeschränkung', '/images/movies/nowshowing/it_s_christmas_weihnachten_mit_jonas_kaufmann.jpg', '/images/movies/nowshowing/it_s_christmas_weihnachten_mit_jonas_kaufmann-slider.png', '/images/tickets/nowshowing/it_s_christmas_weihnachten_mit_jonas_kaufmann-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 'KEIN WEG ZURÜCK', 'Vejen hjem', 'Drama / Thriller', '98 Minuten', '', 'Nikolaj Lie Kaas, Albert Rudbeck Lindhardt, Arian Kashef', 'Ein Vater begibt sich auf eine gefährliche Reise, um seinen Sohn zu retten. Kein Weg zurück ist ein spannungsgeladener Thriller über Schuld, Hoffnung und moralische Grenzen.', '2024', 'Dänemark', '01.01.2024', 'ab 16 Jahren', '/images/movies/nowshowing/kein_weg_zur_ck.jpg', '/images/movies/nowshowing/kein_weg_zur_ck-slider.png', '/images/tickets/nowshowing/kein_weg_zur_ck-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 'MAD HEIDI', 'Mad Heidi', 'Horror / Action', '96 Minuten', '', 'Alice Lucy, Casper Van Dien, David Schofield, Max Rüdlinger', 'In einer dystopischen Version der Schweiz wird aus der bekannten Alpenidylle ein brutales Unterdrückungssystem. Mad Heidi interpretiert den klassischen Stoff radikal neu.', '2022', 'Schweiz', '01.01.2022', 'FSK 18', '/images/movies/nowshowing/mad_heidi.jpg', '/images/movies/nowshowing/mad_heidi-slider.png', '/images/tickets/nowshowing/mad_heidi-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 'MARCO', 'Marco', 'Action', '142 Minuten', '', 'Unni Mukundan, Siddique, Jagadish, Kubir Duhan Singh', 'Ein kompromissloser Actionfilm über Loyalität, Verrat und Rache. Marco erzählt die Geschichte eines Mannes, der sich in einer Welt aus Gewalt und Machtkämpfen behaupten muss.', '2024', 'Indien', '01.01.2024', 'ab 16 Jahren', '/images/movies/nowshowing/marco.jpg', '/images/movies/nowshowing/marco-slider.png', '/images/tickets/nowshowing/marco-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 'MONSIEUR ROBERT KENNT KEIN PARDON', 'Les vengeances de Maître Poutifard', 'Komödie', '90 Minuten', '', 'Christian Clavier, Isabelle Nanty, Jennie Anne Walker, Roby Schinasi', 'Ein pensionierter Lehrer holt nach, was er jahrzehntelang unterdrückt hat: Rache an seinen ehemaligen Schülern. Eine charmante Komödie über späte Genugtuung und moralische Grenzen.', '2023', 'Frankreich', '01.01.2023', 'ab 12 Jahren', '/images/movies/nowshowing/monsieur_robert_kennt_kein_pardon.jpg', '/images/movies/nowshowing/monsieur_robert_kennt_kein_pardon-slider.png', '/images/tickets/nowshowing/monsieur_robert_kennt_kein_pardon-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 'NACHBEBEN', 'Det Andet Offer', 'Drama', '92 Minuten', '', 'Trine Dyrholm, Özlem Saglanmak, Mathilde Arcel, Olaf Johannessen', 'Nach einem tragischen medizinischen Zwischenfall gerät das Leben mehrerer Menschen aus dem Gleichgewicht. Nachbeben ist ein intensives Drama über Schuld, Verantwortung und die Folgen einer einzigen Entscheidung.', '2025', 'Dänemark', '01.01.2025', 'ab 12 Jahren', '/images/movies/nowshowing/nachbeben.jpg', '/images/movies/nowshowing/nachbeben-slider.png', '/images/tickets/nowshowing/nachbeben-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 'OVERLORD: THE SACRED KINGDOM', 'Overlord Sei Oukoku-hen', 'Anime / Fantasy / Action', '135 Minuten', '', '', 'Ein episches Fantasy-Abenteuer im Overlord-Universum. The Sacred Kingdom erweitert die Geschichte mit neuen Konflikten und großen Schlachten.', '2024', 'Japan', '01.01.2024', 'ab 16 Jahren', '/images/movies/nowshowing/overlord_the_sacred_kingdom.jpg', '/images/movies/nowshowing/overlord_the_sacred_kingdom-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 'TERESA – EIN LEBEN ZWISCHEN LICHT UND SCHATTEN', 'Mother', 'Drama', '103 Minuten', '', 'Noomi Rapace, Sylvia Hoeks, Nikola Ristanovski', 'Eine Frau zwischen Glauben, Zweifel und persönlichem Opfer. Teresa – Ein Leben zwischen Licht und Schatten ist ein intensives Drama über Identität, Verantwortung und innere Zerrissenheit.', '2025', 'Belgien / Nordmazedonien', '01.01.2025', 'ab 12 Jahren', '/images/movies/nowshowing/teresa_ein_leben_zwischen_licht_und_schatten.jpg', '/images/movies/nowshowing/teresa_ein_leben_zwischen_licht_und_schatten-slider.png', '/images/tickets/nowshowing/teresa_ein_leben_zwischen_licht_und_schatten-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 'THE LONGEST WAVE', 'The Longest Wave', 'Dokumentarfilm', '90 Minuten', '', '', 'Eine visuelle Reise zu den spektakulärsten Surfspots der Welt. The Longest Wave verbindet Naturaufnahmen mit persönlichen Geschichten.', '2020', 'USA / Österreich', '01.01.2020', 'ab 0 Jahren', '/images/movies/nowshowing/the_longest_wave.jpg', '/images/movies/nowshowing/the_longest_wave-slider.png', NULL, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 'TRAIN TO BUSAN', 'Train to Busan', 'Action / Horror', '118 Minuten', '', 'Gong Yoo, Ma Dong-seok, Kim Su-an, Jung Yu-mi', 'Während einer Zugfahrt von Seoul nach Busan bricht plötzlich eine mysteriöse Zombie-Epidemie aus. Die Passagiere müssen um ihr Überleben kämpfen.', '2016', 'Südkorea', '01.01.2016', 'ab 16 Jahren', '/images/movies/nowshowing/train_to_busan.png', '/images/movies/nowshowing/train_to_busan-slider.png', '/images/tickets/nowshowing/train_to_busan-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 'ZOMBIE – DAWN OF THE DEAD', 'Dawn of the Dead', 'Horror', '120 Minuten', '', 'David Emge, Ken Foree, Scott H. Reiniger', 'Ein Klassiker des Zombie-Genres: Nach dem Zusammenbruch der Gesellschaft verschanzt sich eine Gruppe Überlebender in einem Einkaufszentrum.', '1978', 'USA', '01.01.1978', 'FSK 18', '/images/movies/nowshowing/zombie_dawn_of_the_dead.jpg', '/images/movies/nowshowing/zombie_dawn_of_the_dead-slider.png', '/images/tickets/nowshowing/zombie_dawn_of_the_dead-ticket.jpg', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    original_title = EXCLUDED.original_title,
    genre = EXCLUDED.genre,
    duration = EXCLUDED.duration,
    director = EXCLUDED.director,
    movie_cast = EXCLUDED.movie_cast,
    description = EXCLUDED.description,
    year = EXCLUDED.year,
    country = EXCLUDED.country,
    release_date = EXCLUDED.release_date,
    fsk = EXCLUDED.fsk,
    poster_path = EXCLUDED.poster_path,
    slider_path = EXCLUDED.slider_path,
    ticket_path = EXCLUDED.ticket_path,
    is_coming_soon = EXCLUDED.is_coming_soon,
    updated_at = CURRENT_TIMESTAMP;

-- Update sequence to continue from the highest ID
SELECT setval('movies_id_seq', (SELECT MAX(id) FROM movies));
